const state={legends:[],legendTypes:[],colors:[],workshops:[],oneCBases:[],selectedLegendId:null,menuMode:'layers',visibleTypes:new Set(),searchTimer:null,drag:null};
const NS='http://www.w3.org/2000/svg';
const els={mapStage:document.getElementById('mapStage'),workshopLayer:document.getElementById('workshopLayer'),legendLayer:document.getElementById('legendLayer'),menuContent:document.getElementById('menuContent'),searchInput:document.getElementById('searchInput'),clearSearchBtn:document.getElementById('clearSearchBtn'),layersBtn:document.getElementById('layersBtn'),addLegendBtn:document.getElementById('addLegendBtn'),logoutBtn:document.getElementById('logoutBtn'),toast:document.getElementById('toast')};
async function init(){try{await apiRequest('/auth/me.php');await loadReferenceData();renderWorkshops();await loadLegends();renderLayersMenu();}catch(e){if(e.status===401)location.href='login.html';else showToast(e.message,true)}}
async function loadReferenceData(){const [types,colors,workshops,bases]=await Promise.all([apiRequest('/legend-types/list.php'),apiRequest('/colors/list.php'),apiRequest('/workshops/list.php'),apiRequest('/one-c-bases/list.php')]);state.legendTypes=types;state.colors=colors;state.workshops=workshops;state.oneCBases=bases;state.visibleTypes=new Set(types.map(t=>Number(t.id)))}
function renderWorkshops(){els.workshopLayer.innerHTML='';const names=new Set();(MAP_CONFIG.workshopPolygons||[]).forEach(w=>{const p=document.createElementNS(NS,'polygon');p.setAttribute('points',w.points.map(x=>x.join(',')).join(' '));p.classList.add('workshop-hitbox');p.dataset.id=w.id;els.workshopLayer.appendChild(p);});}
async function loadLegends(search=''){state.legends=await apiRequest('/legends/list.php',{query:{search}});renderLegends();}
function renderLegends(){els.legendLayer.innerHTML='';state.legends.forEach(l=>{if(!state.visibleTypes.has(Number(l.legend_type_id)))return;const g=document.createElementNS(NS,'g');g.classList.add('legend');g.dataset.id=l.id;g.dataset.typeId=l.legend_type_id;g.setAttribute('transform',`translate(${l.x} ${l.y})`);const c=document.createElementNS(NS,'circle');c.classList.add('legend-body');c.setAttribute('r',Math.min(l.width,l.height)/2);c.setAttribute('fill',l.color_hex);c.setAttribute('fill-opacity','.92');c.setAttribute('stroke','#00204a');c.setAttribute('stroke-width',l.border_width);const label=document.createElementNS(NS,'text');label.classList.add('legend-code');label.textContent=l.type_code||'';label.setAttribute('x',0);label.setAttribute('y',5);const name=document.createElementNS(NS,'text');name.classList.add('legend-name');name.textContent=l.name;name.setAttribute('x',Math.min(l.width,l.height)/2+7);name.setAttribute('y',4);g.append(c,label,name);g.addEventListener('click',e=>{if(state.drag?.moved)return;selectLegend(l.id);if(e.ctrlKey)openLegendCard(l.id)});g.addEventListener('pointerdown',e=>beginDrag(e,g,l));els.legendLayer.appendChild(g)});applySearchHighlight();}
function beginDrag(e,g,l){if(e.button!==0)return;e.preventDefault();const p=screenToMap(e.clientX,e.clientY);state.drag={legend:l,group:g,startX:p.x,startY:p.y,originalX:l.x,originalY:l.y,moved:false};g.classList.add('dragging');const move=ev=>{if(!state.drag)return;const p=screenToMap(ev.clientX,ev.clientY);l.x=clamp(p.x,0,MAP_CONFIG.width);l.y=clamp(p.y,0,MAP_CONFIG.height);if(Math.abs(l.x-state.drag.originalX)+Math.abs(l.y-state.drag.originalY)>2)state.drag.moved=true;g.setAttribute('transform',`translate(${l.x} ${l.y})`)};const end=async()=>{if(!state.drag)return;const cur=state.drag;state.drag=null;g.classList.remove('dragging');window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);if(cur.moved){l.workshop_id=findWorkshopId(l.x,l.y);try{await saveLegend(l);showToast(`Положение сохранено. ${getWorkshopName(l.workshop_id)}`)}catch(err){l.x=cur.originalX;l.y=cur.originalY;g.setAttribute('transform',`translate(${l.x} ${l.y})`);showToast(err.message,true)}}};window.addEventListener('pointermove',move);window.addEventListener('pointerup',end)}
function screenToMap(x,y){const r=els.mapStage.getBoundingClientRect();return{x:(x-r.left)*MAP_CONFIG.width/r.width,y:(y-r.top)*MAP_CONFIG.height/r.height}}
function findWorkshopId(x,y){for(const w of state.workshops){const local=(MAP_CONFIG.workshopPolygons||[]).find(p=>Number(p.id)===Number(w.id));if(local&&pointInPolygon(x,y,local.points))return Number(w.id)}let best=null,bd=Infinity;(MAP_CONFIG.workshopCenters||[]).forEach(c=>{const d=Math.hypot(x-c.x,y-c.y);if(d<bd){bd=d;best=c.id}});return best}
function pointInPolygon(x,y,pts){let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const xi=pts[i][0],yi=pts[i][1],xj=pts[j][0],yj=pts[j][1];if(((yi>y)!=(yj>y))&&(x<(xj-xi)*(y-yi)/((yj-yi)||Number.EPSILON)+xi))inside=!inside}return inside}
function selectLegend(id){state.selectedLegendId=Number(id);document.querySelectorAll('.legend').forEach(e=>e.classList.toggle('selected',Number(e.dataset.id)===state.selectedLegendId))}
async function openLegendCard(id){const l=await apiRequest('/legends/get.php',{query:{id}});state.menuMode='legend';selectLegend(id);els.menuContent.innerHTML=`<h3>${esc(l.name)}</h3><p><b>Вид:</b> ${esc(l.type_name)}</p><p><b>Цех:</b> ${esc(l.workshop_name||'Не определён')}</p><p><b>Координаты:</b> ${Number(l.x).toFixed(1)}, ${Number(l.y).toFixed(1)}</p><p><b>Размер:</b> ${l.width} × ${l.height}</p><p><b>Толщина обводки:</b> ${l.border_width}</p><p><b>Цвет:</b> <span class="color-chip" style="background:${esc(l.color_hex)}"></span> ${esc(l.color_name)}</p><h4>Базы 1С</h4><div>${l.one_c_bases.length?l.one_c_bases.map(b=>`<div>• ${esc(b.name)} — ${esc(b.installed_version||'')}</div>`).join(''):'<span class="muted">Не указаны</span>'}</div><div class="menu-toolbar actions"><button class="btn btn-primary" id="editLegendBtn">Редактировать</button><button class="btn btn-danger" id="deleteLegendBtn">Удалить</button></div>`;document.getElementById('editLegendBtn').onclick=()=>renderLegendEditor(l);document.getElementById('deleteLegendBtn').onclick=()=>deleteLegend(l.id)}
function renderLegendEditor(l,isNew=false){state.menuMode=isNew?'add':'edit';const typeOptions=state.legendTypes.map(t=>`<option value="${t.id}" ${Number(t.id)===Number(l.legend_type_id)?'selected':''}>${esc(t.name)}</option>`).join('');const colorOptions=state.colors.map(c=>`<option value="${c.id}" ${Number(c.id)===Number(l.color_id)?'selected':''}>${esc(c.name)} (${esc(c.hex_code)})</option>`).join('');els.menuContent.innerHTML=`<h3>${isNew?'Добавление легенды':'Редактирование легенды'}</h3><div class="form-grid"><div class="field field-wide"><label>Имя / идентификатор</label><input id="legendName" value="${attr(l.name||'')}" maxlength="200"></div><div class="field"><label>Вид</label><select id="legendType">${typeOptions}</select></div><div class="field"><label>Цвет</label><select id="legendColor">${colorOptions}</select></div><div class="field"><label>Размер</label><input id="legendSize" type="number" min="20" value="${l.width||64}"></div><div class="field"><label>Толщина обводки</label><input id="legendBorder" type="number" min="0" step="0.5" value="${l.border_width||3.2}"></div><div class="field"><label>X</label><input id="legendX" type="number" step="0.1" value="${l.x??1024}"></div><div class="field"><label>Y</label><input id="legendY" type="number" step="0.1" value="${l.y??645}"></div></div><p class="hint">При добавлении легенды можно поставить её прямо мышью: нажмите «Поставить на карту», затем щёлкните нужное место.</p><div class="bases"><h4>Базы 1С</h4><div id="baseRows"></div><button class="btn" id="addBaseBtn" type="button">+ Добавить базу</button></div><div class="menu-toolbar actions"><button class="btn btn-primary" id="saveLegendBtn">${isNew?'Создать':'Сохранить'}</button><button class="btn" id="placeLegendBtn">Поставить на карту</button><button class="btn" id="cancelLegendBtn">Отмена</button></div>`;const rows=document.getElementById('baseRows');(l.one_c_bases||[]).forEach(b=>addBaseRow(rows,b));document.getElementById('addBaseBtn').onclick=()=>addBaseRow(rows);document.getElementById('legendType').onchange=e=>{if(isNew){const t=state.legendTypes.find(x=>Number(x.id)===Number(e.target.value));if(t?.default_color_id)document.getElementById('legendColor').value=t.default_color_id}};document.getElementById('placeLegendBtn').onclick=()=>startMapPlacement();document.getElementById('saveLegendBtn').onclick=async()=>{try{const p=collectLegendForm();p.workshop_id=findWorkshopId(p.x,p.y);if(isNew){const r=await apiRequest('/legends/create.php',{method:'POST',body:p});await loadLegends();showToast('Легенда создана.');openLegendCard(r.id)}else{p.id=l.id;await apiRequest('/legends/update.php',{method:'POST',body:p});await loadLegends();showToast('Легенда сохранена.');openLegendCard(l.id)}}catch(e){showToast(e.message,true)}};document.getElementById('cancelLegendBtn').onclick=()=>l.id?openLegendCard(l.id):renderLayersMenu()}
function startMapPlacement(){els.mapStage.classList.add('placing');showToast('Щёлкните по карте для установки легенды');const handler=e=>{const p=screenToMap(e.clientX,e.clientY);document.getElementById('legendX').value=p.x.toFixed(1);document.getElementById('legendY').value=p.y.toFixed(1);els.mapStage.classList.remove('placing');els.mapStage.removeEventListener('click',handler);showToast(`Координаты: ${p.x.toFixed(1)}, ${p.y.toFixed(1)}. Цех: ${getWorkshopName(findWorkshopId(p.x,p.y))}`)};els.mapStage.addEventListener('click',handler)}
function addBaseRow(c,b={}){const row=document.createElement('div');row.className='base-row';row.innerHTML=`<select class="base-id"><option value="">Выберите базу</option>${state.oneCBases.map(x=>`<option value="${x.id}" ${Number(x.id)===Number(b.one_c_base_id??b.id)?'selected':''}>${esc(x.name)}</option>`).join('')}</select><input class="base-version" placeholder="Версия" value="${attr(b.installed_version||'')}"><button class="btn" type="button">Удалить</button>`;row.querySelector('button').onclick=()=>row.remove();c.appendChild(row)}
function collectLegendForm(){return{name:document.getElementById('legendName').value.trim(),legend_type_id:Number(document.getElementById('legendType').value),color_id:Number(document.getElementById('legendColor').value),x:Number(document.getElementById('legendX').value),y:Number(document.getElementById('legendY').value),width:Number(document.getElementById('legendSize').value),height:Number(document.getElementById('legendSize').value),border_width:Number(document.getElementById('legendBorder').value),shape:'circle',one_c_bases:Array.from(document.querySelectorAll('#baseRows .base-row')).map(r=>({one_c_base_id:Number(r.querySelector('.base-id').value),installed_version:r.querySelector('.base-version').value.trim()})).filter(x=>x.one_c_base_id&&x.installed_version)}}
async function saveLegend(l){return apiRequest('/legends/update.php',{method:'POST',body:{id:l.id,name:l.name,legend_type_id:Number(l.legend_type_id),color_id:Number(l.color_id),x:Number(l.x),y:Number(l.y),width:Number(l.width),height:Number(l.height),border_width:Number(l.border_width),shape:'circle',workshop_id:findWorkshopId(l.x,l.y)}})}
async function deleteLegend(id){if(!confirm('Удалить выбранную легенду?'))return;try{await apiRequest('/legends/delete.php',{method:'POST',body:{id}});await loadLegends();renderLayersMenu();showToast('Легенда удалена.')}catch(e){showToast(e.message,true)}}
function renderLayersMenu(){state.menuMode='layers';els.menuContent.innerHTML=`<h3>Слои</h3><div class="layer-list">${state.legendTypes.map(t=>`<label class="layer-item"><input type="checkbox" data-type-id="${t.id}" ${state.visibleTypes.has(Number(t.id))?'checked':''}><span class="legend-dot" style="background:${esc(t.default_color_hex||'#ddd')}"></span><span>${esc(t.name)}</span></label>`).join('')}</div><h4>Цеха / зоны</h4><div class="workshop-list">${state.workshops.map(w=>`<div class="workshop-row"><span>${esc(w.name)}</span></div>`).join('')}</div>`;els.menuContent.querySelectorAll('input').forEach(i=>i.onchange=()=>{const id=Number(i.dataset.typeId);i.checked?state.visibleTypes.add(id):state.visibleTypes.delete(id);renderLegends()})}
function startAddLegend(){const t=state.legendTypes[0],c=state.colors.find(x=>Number(x.id)===Number(t?.default_color_id))||state.colors[0];renderLegendEditor({name:'',legend_type_id:t?.id,color_id:c?.id,x:MAP_CONFIG.width/2,y:MAP_CONFIG.height/2,width:64,height:64,border_width:3.2,one_c_bases:[]},true)}
function getWorkshopName(id){return id?state.workshops.find(w=>Number(w.id)===Number(id))?.name||'цех не определён':'цех не определён'}
function applySearchHighlight(){document.querySelectorAll('.legend').forEach(e=>e.classList.remove('highlighted'));const q=els.searchInput.value.trim();if(!q)return;document.querySelectorAll('.legend').forEach(e=>e.classList.add('highlighted'))}
function showToast(m,error=false){els.toast.textContent=m;els.toast.classList.toggle('error',error);els.toast.classList.remove('hidden');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>els.toast.classList.add('hidden'),3500)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function attr(v){return esc(v)}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
els.layersBtn.onclick=renderLayersMenu;els.addLegendBtn.onclick=startAddLegend;els.logoutBtn.onclick=async()=>{try{await apiRequest('/auth/logout.php',{method:'POST'})}catch(_){}localStorage.removeItem('mkk_token');location.href='login.html'};els.clearSearchBtn.onclick=async()=>{els.searchInput.value='';await loadLegends('')};els.searchInput.oninput=()=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(async()=>{try{await loadLegends(els.searchInput.value.trim());if(els.searchInput.value.trim()&&!state.legends.length)showToast('Не найдено',true)}catch(e){showToast(e.message,true)}},250)};
init();
